/**
 * @fileoverview gRPC-Web generated client stub for org.cybershuttle.appserver
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.23.2
// source: appItems.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.org = {};
proto.org.cybershuttle = {};
proto.org.cybershuttle.appserver = require('./appItems_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.cybershuttle.appserver.CyberShuttleServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.cybershuttle.appserver.CyberShuttleServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.cybershuttle.appserver.AppsRequest,
 *   !proto.org.cybershuttle.appserver.MyApps>}
 */
const methodDescriptor_CyberShuttleService_GetApps = new grpc.web.MethodDescriptor(
  '/org.cybershuttle.appserver.CyberShuttleService/GetApps',
  grpc.web.MethodType.UNARY,
  proto.org.cybershuttle.appserver.AppsRequest,
  proto.org.cybershuttle.appserver.MyApps,
  /**
   * @param {!proto.org.cybershuttle.appserver.AppsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.cybershuttle.appserver.MyApps.deserializeBinary
);


/**
 * @param {!proto.org.cybershuttle.appserver.AppsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.cybershuttle.appserver.MyApps)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.cybershuttle.appserver.MyApps>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.cybershuttle.appserver.CyberShuttleServiceClient.prototype.getApps =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.cybershuttle.appserver.CyberShuttleService/GetApps',
      request,
      metadata || {},
      methodDescriptor_CyberShuttleService_GetApps,
      callback);
};


/**
 * @param {!proto.org.cybershuttle.appserver.AppsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.cybershuttle.appserver.MyApps>}
 *     Promise that resolves to the response
 */
proto.org.cybershuttle.appserver.CyberShuttleServicePromiseClient.prototype.getApps =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.cybershuttle.appserver.CyberShuttleService/GetApps',
      request,
      metadata || {},
      methodDescriptor_CyberShuttleService_GetApps);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.cybershuttle.appserver.AppRequest,
 *   !proto.org.cybershuttle.appserver.ListItems>}
 */
const methodDescriptor_CyberShuttleService_GetItems = new grpc.web.MethodDescriptor(
  '/org.cybershuttle.appserver.CyberShuttleService/GetItems',
  grpc.web.MethodType.UNARY,
  proto.org.cybershuttle.appserver.AppRequest,
  proto.org.cybershuttle.appserver.ListItems,
  /**
   * @param {!proto.org.cybershuttle.appserver.AppRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.cybershuttle.appserver.ListItems.deserializeBinary
);


/**
 * @param {!proto.org.cybershuttle.appserver.AppRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.cybershuttle.appserver.ListItems)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.cybershuttle.appserver.ListItems>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.cybershuttle.appserver.CyberShuttleServiceClient.prototype.getItems =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.cybershuttle.appserver.CyberShuttleService/GetItems',
      request,
      metadata || {},
      methodDescriptor_CyberShuttleService_GetItems,
      callback);
};


/**
 * @param {!proto.org.cybershuttle.appserver.AppRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.cybershuttle.appserver.ListItems>}
 *     Promise that resolves to the response
 */
proto.org.cybershuttle.appserver.CyberShuttleServicePromiseClient.prototype.getItems =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.cybershuttle.appserver.CyberShuttleService/GetItems',
      request,
      metadata || {},
      methodDescriptor_CyberShuttleService_GetItems);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.cybershuttle.appserver.ItemRequest,
 *   !proto.org.cybershuttle.appserver.ItemStatus>}
 */
const methodDescriptor_CyberShuttleService_LaunchItem = new grpc.web.MethodDescriptor(
  '/org.cybershuttle.appserver.CyberShuttleService/LaunchItem',
  grpc.web.MethodType.UNARY,
  proto.org.cybershuttle.appserver.ItemRequest,
  proto.org.cybershuttle.appserver.ItemStatus,
  /**
   * @param {!proto.org.cybershuttle.appserver.ItemRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.cybershuttle.appserver.ItemStatus.deserializeBinary
);


/**
 * @param {!proto.org.cybershuttle.appserver.ItemRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.cybershuttle.appserver.ItemStatus)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.cybershuttle.appserver.ItemStatus>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.cybershuttle.appserver.CyberShuttleServiceClient.prototype.launchItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.cybershuttle.appserver.CyberShuttleService/LaunchItem',
      request,
      metadata || {},
      methodDescriptor_CyberShuttleService_LaunchItem,
      callback);
};


/**
 * @param {!proto.org.cybershuttle.appserver.ItemRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.cybershuttle.appserver.ItemStatus>}
 *     Promise that resolves to the response
 */
proto.org.cybershuttle.appserver.CyberShuttleServicePromiseClient.prototype.launchItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.cybershuttle.appserver.CyberShuttleService/LaunchItem',
      request,
      metadata || {},
      methodDescriptor_CyberShuttleService_LaunchItem);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.cybershuttle.appserver.ItemRequest,
 *   !proto.org.cybershuttle.appserver.ItemStatus>}
 */
const methodDescriptor_CyberShuttleService_StopItem = new grpc.web.MethodDescriptor(
  '/org.cybershuttle.appserver.CyberShuttleService/StopItem',
  grpc.web.MethodType.UNARY,
  proto.org.cybershuttle.appserver.ItemRequest,
  proto.org.cybershuttle.appserver.ItemStatus,
  /**
   * @param {!proto.org.cybershuttle.appserver.ItemRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.cybershuttle.appserver.ItemStatus.deserializeBinary
);


/**
 * @param {!proto.org.cybershuttle.appserver.ItemRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.cybershuttle.appserver.ItemStatus)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.cybershuttle.appserver.ItemStatus>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.cybershuttle.appserver.CyberShuttleServiceClient.prototype.stopItem =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.cybershuttle.appserver.CyberShuttleService/StopItem',
      request,
      metadata || {},
      methodDescriptor_CyberShuttleService_StopItem,
      callback);
};


/**
 * @param {!proto.org.cybershuttle.appserver.ItemRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.cybershuttle.appserver.ItemStatus>}
 *     Promise that resolves to the response
 */
proto.org.cybershuttle.appserver.CyberShuttleServicePromiseClient.prototype.stopItem =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.cybershuttle.appserver.CyberShuttleService/StopItem',
      request,
      metadata || {},
      methodDescriptor_CyberShuttleService_StopItem);
};


module.exports = proto.org.cybershuttle.appserver;

